/**
 * API 호출 실패 시 사용하는 폴백 레시피 풀
 *
 * 식재료 단가 기준 (2024~2025 이마트·홈플러스 기준):
 *   즉석밥(210g) 1,500 | 계란 1개 300 | 두부 1모(300g) 1,500
 *   신라면 1봉 950 | 참치캔(100g) 1,800 | 어묵 150g 2,000
 *   닭가슴살 100g 900 | 돼지고기 앞다리살 100g 1,200 | 고등어 반마리(150g) 1,500
 *   된장 100g 600 | 고추장 100g 700 | 간장 50ml 200
 *   참기름 15ml 450 | 식용유 15ml 50
 *   양파 1개 500 | 대파 1대 500 | 당근 1개 800 | 애호박 1개 1,500
 *   김치 100g 500 | 콩나물 100g 500 | 마늘 1쪽 80 | 청양고추 1개 100
 *   쌀밥 1공기(200g 취사 기준) 200
 *
 * id·time·retail 은 mealPlan.js 폴백 경로에서 슬롯에 맞게 할당됨
 */

export const FALLBACK_POOL = [
  /* ─────────── 초간단 ─────────── */
  {
    name:  '계란후라이 + 즉석밥',
    emoji: '🍳',
    diff:  '초간단',
    mins:  '5분',
    cost:  2200,
    kcal:  510,
    protein: 18.0,
    carbs:   68.0,
    fat:     18.0,
    servings: '1인분',
    sumry:    '즉석밥과 계란후라이로 5분 만에 완성하는 간단 아침식사',
    irdntCode: '',
    ingredients: [
      { name: '즉석밥(햇반)',  amount: '1개 (210g)', price: '약 1,500원' },
      { name: '계란',          amount: '2개',         price: '약 600원'   },
      { name: '식용유',        amount: '1 작은술',    price: '약 50원'    },
      { name: '소금',          amount: '약간',        price: '약 20원'    },
      { name: '참기름',        amount: '1/2 작은술',  price: '약 150원'   },
    ],
    steps: [
      '즉석밥을 전자레인지에 2분 돌린다',
      '팬에 식용유를 두르고 중불로 예열한다',
      '계란을 깨서 넣고 소금 간을 한다',
      '원하는 익힘 정도로 계란후라이를 완성한다',
      '밥 위에 계란후라이를 올리고 참기름을 뿌린다',
    ],
  },
  {
    name:  '신라면 + 계란',
    emoji: '🍜',
    diff:  '초간단',
    mins:  '5분',
    cost:  1400,
    kcal:  580,
    protein: 16.0,
    carbs:   70.0,
    fat:     23.0,
    servings: '1인분',
    sumry:    '가장 친숙한 한국 라면에 계란 하나 추가로 완성',
    irdntCode: '',
    ingredients: [
      { name: '신라면',  amount: '1봉 (120g)', price: '약 950원' },
      { name: '계란',    amount: '1개',         price: '약 300원' },
      { name: '대파',    amount: '1/4대',       price: '약 125원' },
    ],
    steps: [
      '냄비에 물 550ml를 끓인다',
      '면과 스프를 넣고 4분 30초 끓인다',
      '마지막 1분에 계란을 깨서 넣는다',
      '대파를 썰어 올리고 마무리한다',
    ],
  },
  {
    name:  '콩나물국밥',
    emoji: '🥣',
    diff:  '초간단',
    mins:  '10분',
    cost:  2500,
    kcal:  400,
    protein: 11.0,
    carbs:   70.0,
    fat:      8.0,
    servings: '1인분',
    sumry:    '구수한 콩나물국에 즉석밥을 말아 먹는 든든한 한 끼',
    irdntCode: '',
    ingredients: [
      { name: '즉석밥(햇반)', amount: '1개 (210g)', price: '약 1,500원' },
      { name: '콩나물',        amount: '100g',        price: '약 500원'   },
      { name: '김치',          amount: '50g',         price: '약 250원'   },
      { name: '간장',          amount: '1 큰술',      price: '약 100원'   },
      { name: '참기름',        amount: '1 작은술',    price: '약 150원'   },
    ],
    steps: [
      '냄비에 물 300ml와 콩나물을 넣고 뚜껑을 닫고 끓인다',
      '팔팔 끓으면 중불로 줄이고 5분 더 끓인다',
      '간장으로 간을 맞춘다',
      '즉석밥을 전자레인지에 2분 돌린 뒤 그릇에 담는다',
      '콩나물국을 밥에 붓고 참기름을 뿌린다. 김치를 곁들인다',
    ],
  },

  /* ─────────── 보통 ─────────── */
  {
    name:  '두부된장찌개 + 밥',
    emoji: '🥘',
    diff:  '보통',
    mins:  '15분',
    cost:  1900,
    kcal:  410,
    protein: 18.0,
    carbs:   65.0,
    fat:     10.0,
    servings: '1인분',
    sumry:    '두부와 된장으로 만드는 담백한 찌개에 따뜻한 밥 한 그릇',
    irdntCode: '',
    ingredients: [
      { name: '두부',            amount: '반모 (150g)',  price: '약 750원'   },
      { name: '된장',            amount: '1.5 큰술 (40g)', price: '약 240원' },
      { name: '애호박',          amount: '1/4개 (100g)', price: '약 375원'   },
      { name: '대파',            amount: '1/3대',        price: '약 170원'   },
      { name: '멸치다시마육수',  amount: '2컵 (400ml)', price: '약 200원'   },
      { name: '쌀밥',            amount: '1공기 (200g)', price: '약 200원'   },
    ],
    steps: [
      '멸치다시마육수를 냄비에 붓고 중불로 끓인다',
      '된장을 체에 받쳐 풀어 넣는다',
      '두부를 2cm 주사위 모양으로 썰어 넣는다',
      '애호박을 반달 모양으로 썰어 넣고 5분 끓인다',
      '대파를 어슷썰기 해서 넣고 1분 더 끓인다',
    ],
  },
  {
    name:  '참치김치찌개 + 밥',
    emoji: '🥘',
    diff:  '보통',
    mins:  '15분',
    cost:  3500,
    kcal:  520,
    protein: 25.0,
    carbs:   60.0,
    fat:     17.0,
    servings: '1인분',
    sumry:    '참치캔과 김치로 만드는 진하고 칼칼한 찌개',
    irdntCode: '',
    ingredients: [
      { name: '참치캔',    amount: '1캔 (100g)',  price: '약 1,800원' },
      { name: '묵은지·김치', amount: '150g',      price: '약 750원'   },
      { name: '두부',      amount: '1/4모 (75g)', price: '약 375원'   },
      { name: '대파',      amount: '1/3대',       price: '약 170원'   },
      { name: '청양고추',  amount: '1개',         price: '약 100원'   },
      { name: '고추장',    amount: '1 작은술 (10g)', price: '약 70원' },
      { name: '쌀밥',      amount: '1공기 (200g)', price: '약 200원'  },
    ],
    steps: [
      '냄비에 참치캔 기름을 두르고 김치를 중불에 2분 볶는다',
      '물 300ml를 붓고 센불로 끓인다',
      '참치살을 넣고 고추장으로 간을 맞춘다',
      '두부를 큼직하게 썰어 넣고 5분 끓인다',
      '대파·청양고추를 넣고 1분 더 끓인다',
    ],
  },
  {
    name:  '계란볶음밥',
    emoji: '🍚',
    diff:  '보통',
    mins:  '10분',
    cost:  1400,
    kcal:  540,
    protein: 16.0,
    carbs:   78.0,
    fat:     18.0,
    servings: '1인분',
    sumry:    '냉장고 속 자투리 채소로 만드는 고소한 볶음밥',
    irdntCode: '',
    ingredients: [
      { name: '쌀밥',     amount: '1공기 (200g)', price: '약 200원' },
      { name: '계란',     amount: '2개',          price: '약 600원' },
      { name: '당근',     amount: '1/4개 (50g)',  price: '약 200원' },
      { name: '대파',     amount: '1/4대',        price: '약 125원' },
      { name: '간장',     amount: '1 큰술',       price: '약 100원' },
      { name: '참기름',   amount: '1 작은술',     price: '약 150원' },
      { name: '식용유',   amount: '1 큰술',       price: '약 50원'  },
    ],
    steps: [
      '당근과 파를 잘게 다진다',
      '팬에 식용유를 두르고 당근을 1분 볶는다',
      '밥을 넣고 고슬고슬해질 때까지 볶는다',
      '한쪽으로 밀어두고 빈 자리에 계란을 깨서 스크램블한다',
      '계란과 밥을 섞은 뒤 간장·참기름·파로 마무리한다',
    ],
  },

  /* ─────────── 도전 ─────────── */
  {
    name:  '닭가슴살볶음밥',
    emoji: '🍗',
    diff:  '도전',
    mins:  '20분',
    cost:  2000,
    kcal:  560,
    protein: 32.0,
    carbs:   72.0,
    fat:     15.0,
    servings: '1인분',
    sumry:    '닭가슴살로 단백질을 보충하는 다이어트식 볶음밥',
    irdntCode: '',
    ingredients: [
      { name: '닭가슴살',  amount: '100g',         price: '약 900원' },
      { name: '쌀밥',      amount: '1공기 (200g)', price: '약 200원' },
      { name: '계란',      amount: '1개',          price: '약 300원' },
      { name: '당근',      amount: '1/4개 (50g)',  price: '약 200원' },
      { name: '양파',      amount: '1/4개 (60g)',  price: '약 125원' },
      { name: '간장',      amount: '1 큰술',       price: '약 100원' },
      { name: '참기름',    amount: '1 작은술',     price: '약 150원' },
      { name: '식용유',    amount: '1 큰술',       price: '약 50원'  },
    ],
    steps: [
      '닭가슴살을 잘게 썰어 소금·후추로 밑간한다',
      '팬에 식용유를 두르고 닭가슴살을 완전히 익힌다',
      '당근·양파를 잘게 썰어 함께 볶는다',
      '밥을 넣고 고슬고슬하게 볶는다',
      '한쪽에 계란을 깨서 스크램블한 뒤 밥과 섞는다',
      '간장·참기름으로 간을 맞춰 마무리한다',
    ],
  },
  {
    name:  '고등어구이 + 밥 + 김치',
    emoji: '🐟',
    diff:  '도전',
    mins:  '25분',
    cost:  2400,
    kcal:  550,
    protein: 28.0,
    carbs:   55.0,
    fat:     22.0,
    servings: '1인분',
    sumry:    '오메가3 풍부한 고등어를 바삭하게 구워내는 건강 한 끼',
    irdntCode: '',
    ingredients: [
      { name: '냉동고등어', amount: '반마리 (150g)', price: '약 1,500원' },
      { name: '쌀밥',       amount: '1공기 (200g)', price: '약 200원'   },
      { name: '김치',       amount: '100g',         price: '약 500원'   },
      { name: '마늘',       amount: '2쪽',          price: '약 160원'   },
      { name: '소금',       amount: '약간',         price: '약 20원'    },
      { name: '식용유',     amount: '1 큰술',       price: '약 50원'    },
    ],
    steps: [
      '고등어는 흐르는 물에 씻어 키친타월로 물기를 닦는다',
      '소금을 앞뒤로 뿌리고 10분간 재운다',
      '팬에 식용유를 두르고 중약불에서 껍질 면부터 7분 굽는다',
      '뒤집어서 5분 더 굽는다 (속이 완전히 익을 때까지)',
      '밥과 김치를 곁들여 낸다',
    ],
  },
  {
    name:  '제육볶음 + 밥',
    emoji: '🍖',
    diff:  '도전',
    mins:  '25분',
    cost:  3100,
    kcal:  650,
    protein: 28.0,
    carbs:   65.0,
    fat:     26.0,
    servings: '1인분',
    sumry:    '칼칼한 고추장 양념에 돼지고기를 볶아내는 인기 반찬',
    irdntCode: '',
    ingredients: [
      { name: '돼지고기 앞다리살', amount: '150g',         price: '약 1,800원' },
      { name: '고추장',            amount: '2 큰술 (30g)', price: '약 210원'   },
      { name: '양파',              amount: '1/2개 (120g)', price: '약 250원'   },
      { name: '대파',              amount: '1/3대',        price: '약 170원'   },
      { name: '마늘',              amount: '2쪽',          price: '약 160원'   },
      { name: '간장',              amount: '1 큰술',       price: '약 100원'   },
      { name: '참기름',            amount: '1 작은술',     price: '약 150원'   },
      { name: '식용유',            amount: '1 큰술',       price: '약 50원'    },
      { name: '쌀밥',              amount: '1공기 (200g)', price: '약 200원'   },
    ],
    steps: [
      '돼지고기를 한 입 크기로 썬다',
      '고추장·간장·다진 마늘을 섞어 양념장을 만든다',
      '돼지고기에 양념장을 넣고 10분 재운다',
      '팬에 식용유를 두르고 센불로 고기를 볶는다',
      '고기가 익으면 양파·대파를 넣고 2분 더 볶는다',
      '참기름을 두르고 불을 끈다. 밥과 함께 낸다',
    ],
  },
]

/**
 * @deprecated 구버전 호환용 — 새 코드는 FALLBACK_POOL 사용
 */
export const FALLBACK_MEALS = FALLBACK_POOL.slice(0, 3).map((r, i) => ({
  ...r,
  id:     ['breakfast', 'lunch', 'dinner'][i],
  time:   ['아침', '점심', '저녁'][i],
  retail: Math.ceil((r.cost * 2.5) / 500) * 500,
}))
